### ISSUE TITLE
Capitalization Error in 'names' function

### ISSUE THREAD

**Issue by ericshaphran** [roshnikatrak/issues-lab#1]
Hi Roshni,
Line 23 reads `Names(storms)`, but the function won't work unless it is changed to `names`

https://github.com/roshnikatrak/issues-lab/blob/f07296375e24e4a7312a6c4c82810e635af31e93/got_issues.Rmd#L23

**Comment by roshnikatrak** [comment]
Fixed function, changed to `names()`
