### ISSUE TITLE
Theme Change Suggestion

### ISSUE THREAD

**Issue by ericshaphran** [roshnikatrak/issues-lab#2]
Hi Roshni,
I noticed that you are using `theme_void()` in line 37, but the visualization may not appear with that theme. May I suggest using `theme_minimal()` instead?

https://github.com/roshnikatrak/issues-lab/blob/f07296375e24e4a7312a6c4c82810e635af31e93/got_issues.Rmd#L37

**Comment by roshnikatrak** [comment]
Changed to `theme_minimal()` for better visualization
