### ISSUE TITLE
Typo in Step 1 Header

### ISSUE THREAD

**Issue by ericshaphran** [roshnikatrak/issues-lab#3]
Hi Roshni,

I think you have a typo in your Step 1 header. I think you meant to type "Exploring."

https://github.com/roshnikatrak/issues-lab/blob/f07296375e24e4a7312a6c4c82810e635af31e93/got_issues.Rmd#L12

**Comment by roshnikatrak** [comment]
Fixed the typo, changed to "Exploring"
